AWSTemplateFormatVersion: 2010-09-09
Description: Creates routes for the SubNetRouteTable declared in VPC.yaml.
Parameters: 
    EnvironmentName: 
        Description: "A prefix for the resource names."
        Type: String
        Default: MyVPC
    
Resources:
    InternetRoute:
        Type: AWS::EC2::Route
        Properties:
            RouteTableId: 
                Fn::ImportValue: 
                    !Sub "SubNetRouteTableId-${EnvironmentName}"
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId:
                Fn::ImportValue:
                    !Sub "InternetGatewayId-${EnvironmentName}"
    PublicSubNetAAssociatedToInterntRoute:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties: 
            RouteTableId:
                Fn::ImportValue:
                    !Sub "SubNetRouteTableId-${EnvironmentName}"
            SubnetId:
                Fn::ImportValue:
                    !Sub "PublicSubNetAId-${EnvironmentName}"                    
    PublicSubNetBAssociatedToInterntRoute:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties: 
            RouteTableId:
                Fn::ImportValue:
                    !Sub "SubNetRouteTableId-${EnvironmentName}"
            SubnetId:
                Fn::ImportValue:
                    Sub "PublicSubNetBId-${EnvironmentName}"
            
            