AWSTemplateFormatVersion: 2010-09-09
Description: Creates a segmented VPC wit 4 subnets (2 publics, 2 privates).
Parameters: 
    EnvironmentName: 
        Description: "A prefix for the resource names."
        Type: String
        Default: MyVPC
    VpcCIDR:
        Description: IP range of the VPC in CIDR notation.
        Type: String
        Default: 10.0.0.0/16
    PublicSubNetACIDR:
        Description: IP range for the public SubNet A.
        Type: String
        Default: 10.0.0.0/24
    PublicSubNetBCIDR:
        Description: IP range for the public SubNet B.
        Type: String
        Default: 10.0.2.0/24
    PrivateSubNetACIDR:
        Description: IP range for the private SubNet A.
        Type: String
        Default: 10.0.3.0/24
    PrivateSubNetBCIDR:
        Description: IP range for the private SubNet B.
        Type: String
        Default: 10.0.4.0/24
    
Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: !Ref VpcCIDR
            Tags:
                - Key: Name
                  Value: !Ref EnvironmentName
    
    PublicSubNetA:
        Type: AWS::EC2::Subnet
        Properties:
            CidrBlock: !Ref PublicSubNetACIDR
            VpcId: !Ref VPC
            Tags:
                - key: Name
                  Value: !Join ["-", ["PublicSubNetA", !Ref EnvironmentName]]
            
        
